[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"
NETLIFY_USE_PNPM = "true"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "https://asherkhan.netlify.app/*"
to = "https://asherkhan.ca/:splat"
status = 302
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200